### ISSUE TITLE
Repo ละเมิดสัญญา GPL

### ISSUE THREAD

**Issue by secretdataz** [be1stmaster/TH-Steam#1]
ก๊อปโค้ดมาทั้งดุ้น ไม่ทำตาม License ต้นฉบับ
แล้วแปะลิงค์โดเนทตัวเอง
น่าเกลียดไปไหมครับ?

**Comment by pixelart7** [comment]
+1 เห็นด้วยครับ เป็นการกระทำที่ไม่ดีอย่างมาก  อยากให้ "ผู้พัฒนา" ของ repo นี้ออกมาแสดงความเห็นหน่อยครับ

**Comment by be1stmaster** [comment]
# ต้องขออภัยเป็นอย่างสูงด้วยครับผม

คือจริงๆ ก่อนหน้านี้ในอีกกลุ่มเฟซบุ๊คผมได้แจ้งไปละ ว่าผมแปลไทยมาให้
(โดยก่อนหน้านั้นผมได้โพสของคุณ mig4ng ไปแล้ว เพราะฉนั้นทุกคนน่าจะรู้ว่าผมนำของคุณ mig4ng มาแปล มิได้เจตนาจะบอกว่าสร้างขึ้นมาเองครับ ต้องขออภัยจริงๆ ในส่วนๆ นี้)
แต่ลบออกไปตอนแก้ Code ว่าจะใส่ใหม่ลืมใส่จริงๆ (พูดไปเหมือนอ้างแฮะ)

## ขอแก้ตัวด้วยการแก้บนแบนเนอร์เลยละกัน

ต้องขออภัยเป็นอย่างสูงและขอขอบคุณสำหรับการตักเตือนในครั้งนี้ครับ คราวหน้า สัญญาจะไม่ให้เกิดขึ้นอีกครับ

และเดี๋ยวผมจะทำการลบ Link Donate ออกจากตัวหน้าสคริป เหลือไว้เพียงใน Readme พอครับ
เพื่อเป็นการรับผิดชอบ และแสดงเจตนาจริงๆ ว่าเป็นแค่เพียงอยากแปลมาให้ใช้งานในกลุ่มจริงๆ เพราะโพสภาษาอังกฤษของคุณ mig4ng แล้วหลายๆ คนเค้างงกัน
(เพราะที่ใส่ลิงค์ไป ก็ยังมิได้มีใครมากดบริจาคของ มีแต่กดมาขอแทนด้วยซ้ำ - -*)

**Comment by be1stmaster** [comment]
และเดี๋ยวผมจะทำการลบ Like Donate ออกจากตัวหน้าสคริป เหลือไว้เพียงใน Readme พอครับ
เพื่อเป็นการรับผิดชอบ และแสดงเจตนาจริงๆ ว่าเป็นแค่เพียงอยากแปลมาให้ใช้งานในกลุ่มจริงๆ เพราะโพสภาษาอังกฤษของคุณ mig4ng แล้วหลายๆ คนเค้างงกัน
